#!/bin/sh

set -eu

remote_name=${1-}
remote_url=${2-}

case "$remote_url" in
  *huutrungle2001/veilbid-flare.git)
    exit 0
    ;;
  *)
    echo "VeilBid Flare push blocked: remote is not huutrungle2001/veilbid-flare.git" >&2
    echo "remote=${remote_name} url=${remote_url}" >&2
    exit 1
    ;;
esac
