import { chmodSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

const requiredIndexerVariables = [
  "FCC_INDEXER_HOST",
  "FCC_INDEXER_PORT",
  "FCC_INDEXER_DATABASE",
  "FCC_INDEXER_USER",
  "FCC_INDEXER_PASSWORD",
];

function requiredText(environment, name) {
  const value = environment[name]?.trim();
  if (!value) throw new Error(`${name}_MISSING`);
  if (/\p{Cc}/u.test(value)) throw new Error(`${name}_INVALID`);
  return value;
}

function tomlString(value) {
  return JSON.stringify(value);
}

function assertAddress(value, name) {
  if (!/^0x[0-9a-fA-F]{40}$/.test(value ?? "")) {
    throw new Error(`${name}_INVALID`);
  }
  return value;
}

export function renderCoston2ProxyConfig({ environment, manifest }) {
  for (const name of requiredIndexerVariables) requiredText(environment, name);
  const indexerPort = Number(requiredText(environment, "FCC_INDEXER_PORT"));
  if (!Number.isSafeInteger(indexerPort) || indexerPort < 1 || indexerPort > 65_535) {
    throw new Error("FCC_INDEXER_PORT_INVALID");
  }

  const redisEndpoint = environment.FCC_PROXY_REDIS_ENDPOINT?.trim() || "redis:6379";
  if (/\p{Cc}/u.test(redisEndpoint) || !/^[A-Za-z0-9._-]+:\d{1,5}$/.test(redisEndpoint)) {
    throw new Error("FCC_PROXY_REDIS_ENDPOINT_INVALID");
  }

  const contracts = manifest.contracts;
  const flareSystemsManager = assertAddress(
    contracts.flareSystemsManager,
    "FLARE_SYSTEMS_MANAGER",
  );
  const relay = assertAddress(contracts.relay, "RELAY");
  const voterRegistry = assertAddress(contracts.voterRegistry, "VOTER_REGISTRY");

  return `# Generated by pnpm flare:proxy:config. Contains indexer credentials.
# Keep this file local, mode 0600, and mount it read-only into tee-proxy.
redis_port = ${tomlString(redisEndpoint)}
chain_id = ${manifest.network.chainId}
private_key_variable = "PROXY_PRIVATE_KEY"
initial_signing_policy_offset = 2
signing_policy_fetch_interval = "20s"
machine_path_list_fetch_interval = "10m"
db_sync_max_sleep_time = "10m"

[db]
host = ${tomlString(requiredText(environment, "FCC_INDEXER_HOST"))}
port = ${indexerPort}
database = ${tomlString(requiredText(environment, "FCC_INDEXER_DATABASE"))}
username = ${tomlString(requiredText(environment, "FCC_INDEXER_USER"))}
password = ${tomlString(requiredText(environment, "FCC_INDEXER_PASSWORD"))}
log_queries = false

[logging]
level = "INFO"
file = ""
max_file_size = 0
console = true

[addresses]
flare_systems_manager = ${tomlString(flareSystemsManager)}
relay = ${tomlString(relay)}
voter_registry = ${tomlString(voterRegistry)}

[ports]
internal = "6661"
external = "6662"

[info_timing]
initial_timeout = "5m"
cycle_internal = "10s"
cycle_queue_response_wait = "30s"

[voting]
proposal_expiration = "120s"
max_pending_request = 100
history_size = 3
finalized_buffer_size = 10
max_provider_vote = 0.025

[storage]
action_ttl = "336h"
result_ttl = "336h"
submit_result_ttl = "30m"
backup_ttl = "192h"

[direct]
enable = true
api_key = ""
api_key_variable = "FCC_DIRECT_API_KEY"
api_key_optional = false
max_body_size = 1048576

[attestation]
enable = true
allow_magic_pass = true

[metrics]
enable = false
`;
}

export function writePrivateProxyConfig(path, source) {
  mkdirSync(dirname(path), { recursive: true, mode: 0o700 });
  writeFileSync(path, source, { encoding: "utf8", mode: 0o600 });
  chmodSync(path, 0o600);
}
